package main

// a has is a fixed-length string or a byte array generated by a hash function.


type TorrentFile struct {
    Announce    string
    InfoHash    [20]byte // this is a single array with the length of 20 bytes
    PieceHashes [][20]byte
    PieceLength int
    Length      int
    Name        string
}

func (bto bencodeTorrent) ToTorrentFile() (TorrentFile, error) {
// …
    torrentFile := TorrentFile{} 
    return torrentFile, nil
}
